In [151]:
import numpy as np


board = """
031004700
649200080
027610409
962078000
005009603
300500000
090800010
018005030
753000024"""

board = """
400000805
030000000
000700000
020000060
000080400
000010000
000603070
500200000
104000000"""


In [13]:
def grid_from_string( sudoku_numbers ):
    grid = np.array([[int(i) for i in line] for line in sudoku_numbers.split()])
    return grid

In [16]:
def check_sudoku(grid):
    """ Return True if grid is a valid Sudoku square, otherwise False. """
    for i in range(9):
        # j, k index top left hand corner of each 3x3 tile
        j, k = (i // 3) * 3, (i % 3) * 3
        print("i is ", i)
        if len(set(grid[i,:])) != 9 or len(set(grid[:,i])) != 9\
                   or len(set(grid[j:j+3, k:k+3].ravel())) != 9:
            return False
    return True

In [17]:
# Turn the provided string, sudoku, into an integer array
grid = grid_from_string( board )
print(grid)

if check_sudoku(grid):
    print('grid valid')
else:
    print('grid invalid')

[[4 0 0 0 0 0 8 0 5]
 [0 3 0 0 0 0 0 0 0]
 [0 0 0 7 0 0 0 0 0]
 [0 2 0 0 0 0 0 6 0]
 [0 0 0 0 8 0 4 0 0]
 [0 0 0 0 1 0 0 0 0]
 [0 0 0 6 0 3 0 7 0]
 [5 0 0 2 0 0 0 0 0]
 [1 0 4 0 0 0 0 0 0]]
i is  0
grid invalid


In [146]:
def display(grid):
    sep = " "
    cross = " + "
    vbar = "| "
    xbar = "-"*12
    line = "  "
    print(line)
    for i in range(9):
        if i in (3,6):
            print("--------+-------+--------")
        line = vbar
        for j in range(9):
            line += str(grid[i,j]) + sep
            if j in (2,5):
                line += vbar
        
        line += vbar
        print( line )

In [217]:
def solve(grid):

    count = 0
    for i in range(9):
        for j in range(9):
            
            if grid[i,j] == 0:     
                for n in possible_vals( i, j, grid ):
                    grid[i,j] = n
                    solve(grid)
                    grid[i,j] = 0                
                return 

    display( grid )
    print("")
     


def possible( r, c, n, grid ):
    
    print(grid[r,:])
    if n in grid[r,:]:
        return False 
    elif n in grid[:,c]:
        return False
    elif n in smallgrid( r,c,grid):
        return False 
    else:
        return True 

def smallgrid( r, c, grid ):
    rr = r//3*3
    cc = c//3*3

    return grid[rr:rr+3, cc:cc+3]

              
%time solve( grid_from_string(board2))



| 6 4 9 | 8 3 1 | 7 5 2 | 
| 8 2 7 | 5 4 9 | 3 1 6 | 
| 5 3 1 | 6 7 2 | 4 8 9 | 
--------+-------+--------
| 9 6 2 | 4 1 5 | 8 7 3 | 
| 1 8 5 | 7 6 3 | 9 2 4 | 
| 3 7 4 | 9 2 8 | 1 6 5 | 
--------+-------+--------
| 7 5 3 | 2 8 4 | 6 9 1 | 
| 2 1 8 | 3 9 6 | 5 4 7 | 
| 4 9 6 | 1 5 7 | 2 3 8 | 

Wall time: 253 ms


In [206]:
def possible_vals( r, c, grid):
    possibles = np.arange(1,10)
    
    rr = grid[r,:]
    cc = grid[:, c]
    sg = smallgrid(r,c,grid)

    vals = np.concatenate( (rr,cc,sg), axis=None) 

    poss = np.setdiff1d( possibles, vals )
   

    return poss 

possible_vals( 1,1,grid)

array([1, 5, 6, 7, 8, 9])

In [210]:
board2 = """
600030750
020040016
000072000
000010003
180060024
000900065
700004001
000000040
400157038"""

%time solve( grid_from_string(board2))


| 6 4 9 | 8 3 1 | 7 5 2 | 
| 8 2 7 | 5 4 9 | 3 1 6 | 
| 5 3 1 | 6 7 2 | 4 8 9 | 
--------+-------+--------
| 9 6 2 | 4 1 5 | 8 7 3 | 
| 1 8 5 | 7 6 3 | 9 2 4 | 
| 3 7 4 | 9 2 8 | 1 6 5 | 
--------+-------+--------
| 7 5 3 | 2 8 4 | 6 9 1 | 
| 2 1 8 | 3 9 6 | 5 4 7 | 
| 4 9 6 | 1 5 7 | 2 3 8 | 

Wall time: 319 ms


In [156]:
board3= """
080000090
070060210
006048700
800000530
020000000
163000000
000401900
000000070
209700005"""

solve( grid_from_string( board3 ))


| 3 8 2 | 1 7 5 | 4 9 6 | 
| 4 7 5 | 3 6 9 | 2 1 8 | 
| 9 1 6 | 2 4 8 | 7 5 3 | 
--------+-------+--------
| 8 9 4 | 6 2 7 | 5 3 1 | 
| 5 2 7 | 8 1 3 | 6 4 9 | 
| 1 6 3 | 5 9 4 | 8 2 7 | 
--------+-------+--------
| 7 3 8 | 4 5 1 | 9 6 2 | 
| 6 5 1 | 9 8 2 | 3 7 4 | 
| 2 4 9 | 7 3 6 | 1 8 5 | 



In [216]:
%time 
board4 = """
080700300
069800000
000100204
010004002
000057030
800600000
340060000
000000760
000000010"""

%time solve( grid_from_string(board4))

Wall time: 0 ns
  
| 2 8 1 | 7 4 5 | 3 9 6 | 
| 4 6 9 | 8 3 2 | 1 5 7 | 
| 7 3 5 | 1 9 6 | 2 8 4 | 
--------+-------+--------
| 5 1 3 | 9 8 4 | 6 7 2 | 
| 6 9 4 | 2 5 7 | 8 3 1 | 
| 8 7 2 | 6 1 3 | 5 4 9 | 
--------+-------+--------
| 3 4 7 | 5 6 1 | 9 2 8 | 
| 1 5 8 | 4 2 9 | 7 6 3 | 
| 9 2 6 | 3 7 8 | 4 1 5 | 

Wall time: 900 ms


In [181]:
np.unique(grid)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [193]:
poss = [0,1,2,3,4,5,6,7,8,9]
print(poss)
a = np.unique(grid[1,:])
print(a)
for i in a:
    print(" - ", i)
    poss.remove(i)

    print(poss)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0 3]
 -  0
[1, 2, 3, 4, 5, 6, 7, 8, 9]
 -  3
[1, 2, 4, 5, 6, 7, 8, 9]


In [220]:
def recurse(val, oldval, text, limit ):
    new_val = val + oldval
    text += str(new_val)
    if new_val <limit:
        text += ", "
        recurse(new_val, val, text, limit)
    print(text)

recurse (1,0, "", 10)     

1, 2, 3, 5, 8, 13
1, 2, 3, 5, 8, 
1, 2, 3, 5, 
1, 2, 3, 
1, 2, 
1, 


In [19]:
def fibonachi(num):
    if num == 1:
        return 1 
    else:
        return num + fibonachi(num-1)

def looper(num):
    
    sum = 0
    for i in range(1,num+1):
        sum += i
    
    return sum

print( fibonachi(1) == 1)
print( fibonachi(2) == 3)
print( fibonachi(3) == 6)
print( fibonachi(4) == 10)
print( fibonachi(5) == 15)
print( looper(6) == 21)

%time print( fibonachi(1000) )
%time print( looper(1000) )  
%time print( looper(10000000))     

True
True
True
True
True
True
500500
Wall time: 1 ms
500500
Wall time: 1.9 ms
50000005000000
Wall time: 1.04 s


In [21]:
print( True + True  )

2


In [27]:

a = 1
b = 2
print( a == b )
print( a, b )

a = b

print( a == b )
print( a, b )

False
1 2
True
2 2


In [29]:
print( abs(10) )
print( abs( -10 ))

10
10


In [31]:
(100-91)<10


True